# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Following the White Rabbit
email: kutty.a@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog will contain notes I gather while following the white rabbit into the magical world of software applications.
  Stay tuned for notes on Test Automation, Performance Testing and Web and Mobile app development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://arunkutty.github.io" # the base hostname & protocol for your site
twitter_username: kuttya
github_username:  arunkutty

# Build settings
markdown: kramdown
host: 0.0.0.0
port: 9000