# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Arun N. Kutty
email: kutty.a@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Technical notes, wins, fails and more.
  Stay tuned for notes on power use of IBM Rational Test Automation and performance testing tools.
  And some tidbits on Web and Mobile app development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://arunkutty.github.io" # the base hostname & protocol for your site
twitter_username: kuttya
github_username:  arunkutty

# Build settings
markdown: kramdown
host: 0.0.0.0
port: 9000